# General Settings
spring.application.name=NeoHire
server.port=5002

# Global Settings
spring.h2.console.enabled=true
spring.profiles.active=dev
server.tomcat.connection-timeout=600s
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
spring.jpa.hibernate.ddl-auto=update
public.urls=/user/login
security.secret=code-with-sahbaan-neo-Hire-Secret
access.token.expiry.in.hour=24

# Open AI Settings
spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=1

# PG_VECTOR Settings
spring.ai.openai.embedding.options.model=text-embedding-3-large
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=3072
spring.ai.vectorstore.pgvector.schema-validation=true


